import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  gradient: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },

  inputWrapper: {
    borderColor: "#fff",
    borderWidth: 3,
    borderStyle: "solid",
    borderRadius: 50,
    margin: 12,
    width: "80%",
    paddingHorizontal: 25,
    paddingVertical: 15,
    fontSize: 18,
    color: "#fff",
  },
  input: { fontSize: 18, color: "#fff", width: "85%" },
  inputIcon: {
    backgroundColor: "#fff",
    borderRadius: 60,
    padding: 0,
    width: 45,
    height: 45,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    right: 6,
    top: 6,
  },
  inputIconHidden: {
    display: "none",
  },
  title: {
    fontSize: 30,
    color: "#fff",
    fontWeight: "700",
    marginBottom: 25,
  },
  text: {
    color: "#94352F",
    fontSize: 14,
    textAlign: "center",
    margin: 15,
    width: "70%",
  },
  textHeavy: {
    color: "#86282A",
    textDecorationLine: "underline",
    fontWeight: "700",
    fontSize: 14,
  },
  submit: {
    backgroundColor: "#FFBB31",
    padding: 10,
    shadowColor: "#000",
    shadowOffset: { width: 15, height: 15 },
    shadowOpacity: 0.2,
    borderRadius: 50,
    margin: 15,
    marginBottom: 25,
  },
  submitBack: {
    backgroundColor: "#fff",
    padding: 10,
    shadowColor: "#000",
    shadowOffset: { width: 15, height: 15 },
    shadowOpacity: 0.2,
    borderRadius: 50,
    margin: 15,
    marginBottom: 25,
  },
  socialWrapper: {
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginBottom: 15,
  },
  social: {
    backgroundColor: "#fff",
    borderRadius: 60,
    marginVertical: 5,
    marginHorizontal: 10,
    padding: 10,
    width: 60,
    height: 60,
    alignItems: "center",
    justifyContent: "center",
  },
});
